# Generated by Django 2.1.5 on 2019-02-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190129_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
